CREATE SEQUENCE SEQ_ADM_USER INCREMENT BY 1 START WITH 15000;
CREATE SEQUENCE SEQ_ADM_USER_ROLE INCREMENT BY 1 START WITH 15000;
CREATE SEQUENCE SEQ_ADM_ROLE INCREMENT BY 1 START WITH 15000;
CREATE SEQUENCE SEQ_ADM_ROLE_PERMISSION INCREMENT BY 1 START WITH 15000;
