CREATE SEQUENCE SEQ_ADM_BOOK INCREMENT BY 1 START WITH 15000;
CREATE SEQUENCE SEQ_ADM_CAREER INCREMENT BY 1 START WITH 15000;
CREATE SEQUENCE SEQ_ADM_STUDENT INCREMENT BY 1 START WITH 15000;
CREATE SEQUENCE SEQ_ADM_LOAN INCREMENT BY 1 START WITH 15000;
