name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to Jenkins
        run: |
          curl -X POST http://54.210.109.1:8080/job/adm-library-system/build \
          --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}